# DIETARY

Carga y visualizacion de los datasets dieteticos.

In [1]:
%load_ext kedro.ipython

[06/05/26 14:52:48] INFO     Using                                                                  ]8;id=14515732;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=14515733;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\framework\project\__init__.py#281\281]8;;\
                             'C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages
                             \kedro\framework\project\rich_logging.yml' as logging configuration.

[06/05/26 14:52:49] INFO     Registered line magic '%reload_kedro'                                   ]8;id=14515740;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=14515741;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#67\67]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=14515747;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=14515748;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#69\69]8;;\

                    INFO     Resolved project path as:                                              ]8;id=14515754;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=14515755;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#193\193]8;;\
                             C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes.
                             To set a different path, run '%reload_kedro <project_root>'

[06/05/26 14:52:49] INFO     No typed parameter requirements found, returning original   ]8;id=14515762;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py\parameter_validator.py]8;;\:]8;id=14515763;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\validation\parameter_validator.py#124\124]8;;\
                             parameters

[06/05/26 14:52:50] INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=14515770;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=14515771;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro_telemetry\plugin.py#273\273]8;;\
                             the product. No personal data or IP addresses are stored on our side. To
                             opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK` environment
                             variables, or create a `.telemetry` file in the current working
                             directory with the contents `consent: false`. To hide this message,
                             explicitly grant or deny consent. Read more at
                             https://docs.kedro.org/en/stable/about/telemetry/

                    INFO     Kedro project Nhanes                                                   ]8;id=14515777;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=14515778;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#159\159]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=14515784;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=14515785;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\ipython\__init__.py#160\160]8;;\
                             'pipelines'

## DR1TOT_J (Total Nutrient Intakes - Day 1)

In [2]:
df = catalog.load("dr1tot_j_dataset")
df

                    INFO     Loading data from dr1tot_j_dataset (GenericDataset)...            ]8;id=14515792;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=14515793;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,93703.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,8.171401e+04,8.244287e+04,1.0,49.0,2.0,2.0,7.0,2.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,93705.0,7.185561e+03,5.640391e+03,1.0,73.0,2.0,2.0,5.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,93706.0,6.463883e+03,5.397605e-79,1.0,86.0,2.0,1.0,NaN,6.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
4,93707.0,1.533378e+04,2.270707e+04,1.0,81.0,2.0,2.0,14.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,102952.0,1.381296e+04,2.868593e+04,1.0,73.0,2.0,2.0,22.0,7.0,4.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
8700,102953.0,5.063236e+04,5.397605e-79,1.0,73.0,2.0,1.0,2.0,7.0,2.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
8701,102954.0,1.108127e+04,8.924895e+03,1.0,76.0,2.0,2.0,2.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8702,102955.0,2.752985e+04,3.629955e+04,1.0,73.0,2.0,2.0,15.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8703,102956.0,6.944741e+04,9.275688e+04,1.0,81.0,2.0,2.0,10.0,5.0,1.0,...,NaN,2.0,NaN,1.0,1.0,2.0,NaN,2.0,NaN,2.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)

## DR2TOT_J (Total Nutrient Intakes - Day 2)

In [3]:
df = catalog.load("dr2tot_j_dataset")
df

[06/05/26 14:52:51] INFO     Loading data from dr2tot_j_dataset (GenericDataset)...            ]8;id=14515798;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=14515799;file://C:\Users\Felipe\Desktop\NHANES_PROJECT\nhanes\.venv\Lib\site-packages\kedro\io\data_catalog.py#1053\1053]8;;\

,SEQN,WTDRD1,WTDR2D,DR2DRSTZ,DR2EXMER,DRABF,DRDINT,DR2DBIH,DR2DAY,DR2LANG,...,DR2TP184,DR2TP204,DR2TP205,DR2TP225,DR2TP226,DR2_300,DR2_320Z,DR2_330Z,DR2BWATZ,DR2TWSZ
0,93703.0,5.397605e-79,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,8.171401e+04,8.244287e+04,1.0,87.0,2.0,2.0,18.0,6.0,1.0,...,3.000000e-03,0.041,5.397605e-79,2.000000e-03,1.000000e-02,2.0,5.397605e-79,5.397605e-79,5.397605e-79,91.0
2,93705.0,7.185561e+03,5.640391e+03,1.0,91.0,2.0,2.0,15.0,4.0,1.0,...,1.000000e-03,0.201,2.000000e-03,1.100000e-02,5.900000e-02,2.0,9.600000e+02,5.397605e-79,9.600000e+02,1.0
3,93706.0,6.463883e+03,5.397605e-79,5.0,NaN,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,93707.0,1.533378e+04,2.270707e+04,1.0,78.0,2.0,2.0,22.0,3.0,1.0,...,1.000000e-03,0.327,4.000000e-03,2.500000e-02,6.100000e-02,3.0,1.020000e+03,7.800000e+02,2.400000e+02,99.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,102952.0,1.381296e+04,2.868593e+04,1.0,43.0,2.0,2.0,51.0,1.0,5.0,...,5.397605e-79,0.045,1.600000e-01,3.000000e-02,1.920000e-01,2.0,6.000000e+02,5.397605e-79,6.000000e+02,4.0
8700,102953.0,5.063236e+04,5.397605e-79,5.0,NaN,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8701,102954.0,1.108127e+04,8.924895e+03,1.0,52.0,2.0,2.0,5.0,2.0,1.0,...,3.000000e-03,0.149,5.000000e-03,1.500000e-02,8.000000e-03,3.0,1.500000e+03,5.397605e-79,1.500000e+03,4.0
8702,102955.0,2.752985e+04,3.629955e+04,1.0,79.0,2.0,2.0,18.0,5.0,1.0,...,5.397605e-79,0.064,2.000000e-03,1.400000e-02,1.000000e-03,1.0,4.800000e+02,5.397605e-79,4.800000e+02,1.0
8703,102956.0,6.944741e+04,9.275688e+04,1.0,53.0,2.0,2.0,15.0,3.0,1.0,...,5.397605e-79,0.010,5.397605e-79,5.397605e-79,5.397605e-79,2.0,5.070000e+02,5.397605e-79,5.070000e+02,1.0

In [ ]:
print(f"Shape: {df.shape}")
df.head()

In [ ]:
df.tail()

In [ ]:
df.dtypes.to_frame("dtype")

In [ ]:
import pandas as pd
nulls = df.isnull().sum()
null_pct = (nulls / len(df) * 100).round(2)
null_df = pd.DataFrame({"nulos": nulls, "porcentaje (%)": null_pct})
null_df.sort_values("porcentaje (%)", ascending=False)